name: Build on Change

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Linux (gcc-15)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GCC
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: 15

      - name: Install Xmake
        run: |
          sudo apt-get update
          sudo apt-get install -y xmake

      - name: Configure Project
        run: |
          cd ${{ github.workspace }}
          xmake f --cc=gcc-15 --cxx=g++-15 -c

      - name: Build
        if: success()
        run: |
          cd ${{ github.workspace }}
          xmake

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xmake
        run: |
          winget install xmake

      - name: Configure Project
        run: |
          cd ${{ github.workspace }}
          xmake f -c

      - name: Build
        if: success()
        run: |
          cd ${{ github.workspace }}
          xmake